"""Add login_id and name to User

Revision ID: e441dadd5e04
Revises: 3aff5c9a5565
Create Date: 2025-04-26 18:25:45.260379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e441dadd5e04'
down_revision = '3aff5c9a5565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_login_id'), ['login_id'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_login_id'))
        batch_op.drop_column('name')
        batch_op.drop_column('login_id')

    # ### end Alembic commands ###
